- hosts: [terraform-ansible]
  tasks:
    - name: criando o arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>feito com terraform e ansible ou nao</h1>
    - name: criando servidor
      shell: "nohup busybox httpd -f -p 8080 &"